name: update issue status if PR

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update linked issue status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const script = require('./script.js')
            return await script({github, context, core})
